# Generated by Django 2.2.2 on 2019-09-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190915_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
